from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.core.database import get_db
from app.models.user import OfficialProfile
from app.schemas.assessment import (
    TriageSubmitIn, 
    TriageResultOut, 
    TriageQuestionPublicOut, 
    TriageOption
)

router = APIRouter()

# Server-side answer key and competency map for the mock questions
MOCK_ANSWER_KEY = {
    "q1": "B",
    "q2": "A",
    "q3": "B",
    "q4": "C",
    "q5": "C"
}

MOCK_COMPETENCY_MAP = {
    "q1": "KCM_FUNC_STAT_04",
    "q2": "KCM_FUNC_SURVEY_02",
    "q3": "KCM_DOM_INDEX_01",
    "q4": "KCM_BEH_ETHICS_03",
    "q5": "KCM_FUNC_STAT_04"
}


@router.get("/questions", response_model=list[TriageQuestionPublicOut])
async def get_triage_questions(
    role: str = Query(..., description="FRAC role code from LTI launch"),
):
    """
    INTENT: Provide the 5-question Baseline Diagnostic Triage.
    This solves the 'Cold Start' problem by establishing immediate KCM baseline
    metrics for brand new junior statistical investigators on day one.
    
    WHY static questions here?
      Unlike the RAG assessment which is dynamically generated by Member 2's AI,
      the triage is a fixed heuristic designed to be extremely fast and reliable
      for immediate profiling before the user even hits the dashboard.
    """
    # Mocked baseline questions for MoSPI (specifically tailored to SIH prototype)
    # In a full production system, these would be fetched from the DB based on the `role`
    return [
        TriageQuestionPublicOut(
            id="q1",
            competency_code=MOCK_COMPETENCY_MAP["q1"],
            questionText="When conducting CAPI data collection in a rural block, what is the primary fallback if the tablet loses GPS sync?",
            options=[
                TriageOption(key="A", text="Abandon the survey and return to HQ"),
                TriageOption(key="B", text="Use manual paper schedules and sync later"),
                TriageOption(key="C", text="Switch the tablet to airplane mode and back"),
                TriageOption(key="D", text="Call the MoSPI helpdesk immediately")
            ]
        ),
        TriageQuestionPublicOut(
            id="q2",
            competency_code=MOCK_COMPETENCY_MAP["q2"],
            questionText="Which sampling frame is typically used by the NSSO for the first stage units in urban areas?",
            options=[
                TriageOption(key="A", text="Urban Frame Survey (UFS) blocks"),
                TriageOption(key="B", text="Gram Panchayat registers"),
                TriageOption(key="C", text="Municipal water billing records"),
                TriageOption(key="D", text="Electoral rolls exclusively")
            ]
        ),
        TriageQuestionPublicOut(
            id="q3",
            competency_code=MOCK_COMPETENCY_MAP["q3"],
            questionText="In the calculation of the Consumer Price Index (CPI), what does the 'base year' represent?",
            options=[
                TriageOption(key="A", text="The year with the highest inflation"),
                TriageOption(key="B", text="A reference year with a defined index value of 100"),
                TriageOption(key="C", text="The current calendar year"),
                TriageOption(key="D", text="The year the surveyor joined the department")
            ]
        ),
        TriageQuestionPublicOut(
            id="q4",
            competency_code=MOCK_COMPETENCY_MAP["q4"],
            questionText="If a respondent refuses to share household income data during an official survey, what is the ethical protocol?",
            options=[
                TriageOption(key="A", text="Estimate the data visually"),
                TriageOption(key="B", text="Threaten legal action under the Collection of Statistics Act"),
                TriageOption(key="C", text="Record as non-response and politely conclude the section"),
                TriageOption(key="D", text="Ask neighbors for the information")
            ]
        ),
        TriageQuestionPublicOut(
            id="q5",
            competency_code=MOCK_COMPETENCY_MAP["q5"],
            questionText="During data cleaning, which of the following is considered an 'outlier'?",
            options=[
                TriageOption(key="A", text="A value perfectly matching the mean"),
                TriageOption(key="B", text="A missing value (NULL)"),
                TriageOption(key="C", text="An observation that lies an abnormal distance from other values"),
                TriageOption(key="D", text="A duplicated row in the dataset")
            ]
        )
    ]


@router.post("/submit", response_model=TriageResultOut)
async def submit_triage(payload: TriageSubmitIn, db: AsyncSession = Depends(get_db)):
    """
    INTENT: Process the triage submission and handle the Cold Start Auto-Upsert.
    When an official finishes the triage, their score is saved. If they don't exist
    in the database (because they just logged in via LTI for the first time), 
    we create their profile on the fly.
    """
    
    if not payload.answers:
        raise HTTPException(status_code=400, detail="No answers provided.")
        
    # Server-side score computation and dynamic gap identification
    correct_count = 0
    total_questions = len(MOCK_ANSWER_KEY)
    gaps_set = set()
    
    for q_id, correct_key in MOCK_ANSWER_KEY.items():
        if payload.answers.get(q_id) == correct_key:
            correct_count += 1
        else:
            gaps_set.add(MOCK_COMPETENCY_MAP[q_id])
            
    computed_score = (correct_count / total_questions) * 100.0

    # INTENT: Fetch user or auto-create if launched via LTI without pre-seeding (Cold Start).
    query = select(OfficialProfile).where(OfficialProfile.user_id == payload.user_id)
    result = await db.execute(query)
    user = result.scalars().first()

    if not user:
        # FIX (Blind Spot #1): Graceful handling of dynamic LTI identities.
        # We use the role_code provided by Member 4 (which got it from Member 3's JWT).
        user = OfficialProfile(
            user_id=payload.user_id,
            frac_role_code=payload.role_code,
            triage_completed=True,
            triage_score=computed_score
        )
        db.add(user)
    else:
        user.triage_completed = True
        user.triage_score = computed_score

    await db.commit()
    await db.refresh(user)

    # INTENT: Return gap analysis payload matching Member 4's expected callback contract.
    return TriageResultOut(
        user_id=user.user_id,
        score=user.triage_score,
        status="completed",
        identified_gaps=list(gaps_set)
    )
